// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zofykfkxvrelpezfvyxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZnlrZmt4dnJlbHBlemZ2eXh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NjI1NjIsImV4cCI6MjA2MjAzODU2Mn0.LX1qerEWb1b_aCQZU4Qy1uRQpxkE5Zs5r91pQHa0Vd8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);